version: "3.9"
services:
  nginx:
    container_name: example-app2_nginx
    image: nginx
    restart: on-failure
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    container_name: example-app2_php-fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    links:
      - redis
  database:
    container_name: example-app2_database
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    container_name: example-app2_adminer
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
  redis:
    container_name: example-app_redis
    image: redis:5
    restart: on-failure
    ports:
      - 6379:6379
  mailhog:
    container_name: example-app2_mailhog
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data:
